version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: voxpop_db
    environment:
      POSTGRES_DB: voxpop_db
      POSTGRES_USER: voxpop
      POSTGRES_PASSWORD: voxpop_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voxpop -d voxpop_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: voxpop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxpop_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./voxpop:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=voxpop_db
      - DB_USER=voxpop
      - DB_PASSWORD=voxpop_secret
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.development

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxpop_celery
    command: celery -A config worker -l INFO -Q default,campaigns,messages_high,messages_low,webhooks,analytics
    volumes:
      - ./voxpop:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=voxpop_db
      - DB_USER=voxpop
      - DB_PASSWORD=voxpop_secret
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.development

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxpop_celery_beat
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./voxpop:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=voxpop_db
      - DB_USER=voxpop
      - DB_PASSWORD=voxpop_secret
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.development

volumes:
  postgres_data:
  redis_data:
